[env:esp32-wroom-32]
platform = espressif32
board = esp32-wroom-32
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    arduino-libraries/WiFi
    ArduinoJson
    pubsubclient
    
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG
