[env:stm32f407vg]
platform = ststm32
board = disco_f407vg
framework = stm32cube
monitor_speed = 115200
upload_protocol = stlink

build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F407xx

lib_deps =
    ArduinoJson
    pubsubclient

[env:stm32f103rb]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
monitor_speed = 115200

build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F103xB
